### ISSUE TITLE
Unable to Edit

### ISSUE THREAD

**Issue by DanielleSherman** [writingatlas/feedback#10]
I can edit lists but not individual stories. I am a copyeditor so I should have superuser access. 
<img width="1451" alt="Screenshot 2023-12-27 at 2 18 16 PM" src="https://github.com/writingatlas/feedback/assets/154077569/5d60ca33-5190-4204-9a85-b2c3ba52aba5">

**Comment by srhm-ca** [comment]
Hi Danielle, thank you for reporting this. It should be fixed. Can you confirm?

**Comment by DanielleSherman** [comment]
Hello,

Yes, it’s fixed! Thanks for your help.

Danielle

**Comment by DanielleSherman** [comment]
Hi again,

I’m having the same problem. Can you restore my editing access?

Thank you,
Danielle

**Comment by srhm-ca** [comment]
Hi Danielle, what email are you logged in under? It should say on your profile.

**Comment by DanielleSherman** [comment]
This email: ***@***.*** ***@***.***>

**Comment by DanielleSherman** [comment]
Hi again,

When I logged back in today, I could edit stories. Not sure what changed but the problem is solved.

Thank you,
Danielle

**Comment by srhm-ca** [comment]
Oh! Great.
