### ISSUE TITLE
unable to save descriptions for "publication" pages 

### ISSUE THREAD

**Issue by Kate-Li-2003** [writingatlas/feedback#16]
I've noticed that, when writing & saving descriptions/website URLs for the pages for publications, saving descriptions will not change the site itself. For example, after pressing "save" on the following page: 

<img width="913" alt="Screenshot 2023-12-29 at 8 32 46 PM" src="https://github.com/writingatlas/feedback/assets/104330786/647b2f2d-ee98-431e-b1cc-6f3c30e5fb56">

no change will take place on the site for the page itself:

<img width="894" alt="Screenshot 2023-12-29 at 8 35 50 PM" src="https://github.com/writingatlas/feedback/assets/104330786/4d138eb9-f974-41b3-b02d-54c9ab4d2085">

When I edit the page, the previously written description/website URL from the last time are still saved in those entries—they just don't appear to make any change to the public version of the site. I've tried editing and saving descriptions for other pages on the website (e.g., saving descriptions for pages that are classified as "collections", not "publications"), and those have worked, so maybe it's just an issue for the pages under publications?

Any help/clarification would be appreciated. Thank you!

**Comment by srhm-ca** [comment]
It's been fixed! Thank you so much for pointing this out.
