### ISSUE TITLE
Year Hyperlink

### ISSUE THREAD

**Issue by bria-char1** [writingatlas/feedback#19]
When clicking a publication year link it goes to the page titled "Short stories published in None" and the same stories appear for every year selected. 

It would be better that the page is titled "Short stories publish in XXXX" and the results correspond to the publication.  

![Screen Shot 2024-01-01 at 4 58 57 PM](https://github.com/writingatlas/feedback/assets/155106233/d4686f3a-3133-4714-9a8e-f82a19873846)
![Screen Shot 2024-01-01 at 4 58 35 PM](https://github.com/writingatlas/feedback/assets/155106233/cf272583-6485-4904-9534-14bd750e5453)
.

**Comment by srhm-ca** [comment]
Fixed! Thanks for pointing this out.
