### ISSUE TITLE
Text font changes in summary (Ex. Abingdon Square by André Aciman)

### ISSUE THREAD

**Issue by cwchen91** [writingatlas/feedback#21]
<img width="694" alt="image" src="https://github.com/writingatlas/feedback/assets/154022186/aae87874-847e-455a-a343-f4ac8c392460">

The font changes in some summaries (pictured above) to Courier font - not sure if this is programming related or just something that happens depending on where the summary is imported from. But it would be nice to have a tool to standardize fonts so that summaries look consistent!

**Comment by jenny8lee** [comment]
Sil will chime in, but I'm going to guess this is a markup thing.

**Comment by srhm-ca** [comment]
Yup, that happens when a paragraph begins with a bunch of spaces. A fellow long ago accidentally inserted a bunch, I wager. I'll have some code automagically strip it out, cheers!
