### ISSUE TITLE
Save and Return Button after Editing a Story

### ISSUE THREAD

**Issue by klairemason25** [writingatlas/feedback#26]
After editing a story, when I click "Save and Return" it takes me to the submission page to The Writing Atlas. This then means I need to click back to stories, publications and then The Atlantic Monthly. I am not sure if there is a way to change this so when someone clicks "save and return" they will be taken back to the story page or a least to their publication, genre or author page etc. 

This is what appears after clicking "save and return" from edit
<img width="682" alt="Screenshot 2024-01-05 at 12 12 14 PM" src="https://github.com/writingatlas/feedback/assets/154637061/a06acca1-da3b-4b3e-888c-1cc60052e0d9">

**Comment by jenny8lee** [comment]
Good point. Thank you. Love these bugs.

**Comment by srhm-ca** [comment]
Hey, that's a great point. Fixed! Thanks for identifying it.
