### ISSUE TITLE
Genre page does not show editable description

### ISSUE THREAD

**Issue by beaphi** [writingatlas/feedback#27]
In any given genre page (e.g. https://writingatlas.com/genre/historical-fiction/), there's an "Edit" link to add a description, but said description is not reflected on the page after an edit.
<img width="831" alt="Screenshot 2024-01-05 at 8 55 17 PM" src="https://github.com/writingatlas/feedback/assets/153690593/13f4561b-79ff-4b7c-b1b9-4de25f62757e">
<img width="796" alt="Screenshot 2024-01-05 at 8 55 13 PM" src="https://github.com/writingatlas/feedback/assets/153690593/20f14f55-b931-42e0-b344-6d55f7a3879c">

**Comment by srhm-ca** [comment]
Fixed! Thanks for pointing it out.
